version: '3.2'
services:
  php:
    build:
      context: docker/dev
      dockerfile: php/Dockerfile
      args:
        HOST_USER: ${USER}
        HOST_USER_ID: ${USER_ID}
    volumes:
      - ./:/var/www/html
