#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace PhpKafka\PhpAvroSchemaGenerator;

if (is_file(__DIR__ . '/../../../autoload.php') === true) {
    include_once __DIR__ . '/../../../autoload.php';
} else {
    include_once __DIR__ . '/../vendor/autoload.php';
}

use Symfony\Component\Console\Application;
use PhpKafka\PhpAvroSchemaGenerator\Command\SubSchemaMergeCommand;
use PhpKafka\PhpAvroSchemaGenerator\Command\SchemaGenerateCommand;

$container = AppContainer::init();

$application = new Application();
$application->addCommands($container['console.commands']);
$application->run();
